name: Android build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Test
        run: ./gradlew testDebugUnitTestCoverageVerification

      - name: Run Test Coverage
        run: ./gradlew createDebugCoverageReport

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/testDebugUnitTestCoverage/jacocoTestReport.csv

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit the badge (if it changed)
        run: |
            if [[ `git status --porcelain` ]]; then
            git config --global user.name 'RahulSharmaTelus'
            git config --global user.email 'rahul.sharma13@telusinternational.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
            fi

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: build/reports/jacoco/testDebugUnitTestCoverage

      - name: Build Project
        run: ./gradlew assemble